[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pulse"
version = "0.1.0"
description = "Enterprise Project Management Platform"
authors = [
    {name = "Pulse", email = "info@pulse.app"},
]
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
]

[tool.bench]
app_type = "frappe"
